# Use postgres/example user/password credentials
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword123
      - POSTGRES_DB=myappdb
    ports:
      - "5432:5432"

    volumes:
          - PostgreSQLdb:/var/lib/postgresql/data # Stockage des données
          - ./db-scripts:/docker-entrypoint-initdb.d/ # Chemin des scripts SQL pour l'initialisation de la base de données

volumes:
  PostgreSQLdb: